### ISSUE TITLE
addError should set errors as an array

### ISSUE THREAD

**Issue by ivanvanderbyl** [DockYard/ember-changeset#100]
When calling validate with multiple validations on a property, `changeset.error.propertName.validations` is an array of messages. However, if you call `changeset.addError('propertyName', 'message')`, then `changeset.error.propertName.validations` will be a string.

This is inconsistent and makes it unclear how to handle validation messages for a property in the UI.

**Comment by dustinfarris** [comment]
Related: https://github.com/DockYard/ember-changeset/pull/52#discussion_r69779078

**Comment by poteto** [comment]
Yup, basically errors being in an array is a quirk from ECV and shouldn't be enforced by this addon. That said, perhaps an `addErrors` method could do so..

**Comment by fotinakis** [comment]
Just a +1, I also just hit this and found that `addError` does not manage the `validations` key as an array like ECV does. Perhaps a `pushError` method?

**Comment by kevinansfield** [comment]
I've also run into this, after the [ember-form-for fix](https://github.com/martndemus/ember-form-for/issues/113) was implemented my local validations were passing but as soon as I get validations back from the server using the [readme instructions](https://github.com/DockYard/ember-changeset#handling-server-errors) it blows up again.

**Comment by fotinakis** [comment]
In case you're interested, here is my workaround to coalesce the errors into an array and only call addError once:

```javascript
  .catch(() => {
    // TODO: clean this up when this issue is addressed:
    // https://github.com/DockYard/ember-changeset/issues/100
    let errorData = {};
    this.get('model.errors').forEach(({attribute, message}) => {
      if (!errorData[attribute]) {
        errorData[attribute] = [];
      }
      errorData[attribute].push(message);
    });
    Object.keys(errorData).forEach((key) => {
      changeset.addError(key, errorData[key]);
    });
  });
```

**Comment by poteto** [comment]
See https://github.com/DockYard/ember-changeset/pull/128
