### ISSUE TITLE
Do not register a change when current "model.value" equals current "changeset.value"

### ISSUE THREAD

**Issue by fknoll** [DockYard/ember-changeset#101]
I am totally in love with ember-changeset! Bravo!

I have this finding:

Given an empty changeset field in a template, e.g. {input type="text" value=changeset.familyName}}. 

Via `controller.set('changeset', new Changeset(model))` this changeset is bound to a newly created `person` record. 

Problem: ember-changeset registers a change after entering this empty field and leaving the field untouched.

Enhancement request: Do not do that!

This request probably could be replaced by a more generic enhancement request: **Do not make or keep a change registration (in changeset.changes), when current "model.value" equals current  "changeset.value"**.

**Comment by poteto** [comment]
This used to be the way ember-changeset was implemented, but it would cause an issue where you could not "remove" a change by restoring a default value:

```js
model.get('foo') // "foo"
changeset.set('foo', 'fo'); // "fo"
changeset.set('foo', 'foo'); // noop
changeset.get('foo', 'fo'); // "fo"
```

**Comment by fknoll** [comment]
My position is purely conceptual - I think an attribute should not be on a change list, if the attribute has not effectively been changed by the user, and (even worse) I think an attribute should not be on a change list just because the user has tabbed though a field bound to the attribute - not typing anything in the field.

However, back to business. My aim is to create an intuitive and consistent user experience.

In an update model/record scenario, I want to inform the user, that she has changed data to be lost, if she leaves the relevant data-entry page/form unsaved.

In a new model/record scenario, I also only want inform the user, that she has changed data to be lost, but ONLY, if the user has indeed typed something into the new model/record - otherwise, I just destroy the record without involving the user.

How do I obtain this user experience using `ember-changeset`? I seems like I neither can rely on `changeset.isPristine` nor `changeset.isDirty` as those values somehow seems to be coupled to (the length of?) the change list?

**Comment by poteto** [comment]
Ah I see, thank you for sharing your use case! I think I can fix the logic for `isPristine` / `isDirty`.

**Comment by poteto** [comment]
Can you give 19f42b30133b5efb26fb657c24a189c4177db916 a whirl @fknoll and let me know if that fixes the issue for you? `isPristine` should now work correctly.

**Comment by fknoll** [comment]
@poteto, thank you so much for your effort on this issue.

I am a GitHub novice!

I executed this command in my project directory:
`ember install https://github.com/DockYard/ember-changeset.git#101-is-pristine-fix`

I got this warning:
`WARNING: Could not figure out blueprint name from: "https://github.com/DockYard/ember-changeset.git#101-is-pristine-fix". Please install the addon blueprint via "ember generate <addon-name>" if necessary.`

Anyway, I think, I successfully installed the "101-is-pristine-fix" branch. In package.json, I have this line:
`"ember-changeset": "git+https://github.com/DockYard/ember-changeset.git#19f42b30133b5efb26fb657c24a189c4177db916",`


I can confirm intended behaviour for an none-empty field/attribute changing value to a none-empty value, e.g. a scenario like this:

```
let userA = { name: 'Bobby', age: 15};
let changesetA = new Changeset(userA);
changesetA.get('isPristine'); // true
changesetA.set('name', 'Kenny');
changesetA.get('isPristine'); // false
changesetA.set('name', Bobby);
changesetA.get('isPristine'); // true
```


If find "**empty**" fields/attributes not working as I would expect, e.g. re-setting an initially empty field back to empty, wrongly keeps `changeset.isPristine === false`:

```
let userB = { name: null, age: 15};
let changesetB = new Changeset(userB);
changesetB.get('isPristine'); // true
changesetB.set('name', 'Kenny');
changesetB.get('isPristine'); // false
changesetB.set('name', null);
changesetB.get('isPristine'); // true, but it should be false!?
```


Also tabbing in and out of an empty field (the underlying object attribute is null or undefined) still sets `changeset.isPristine = false`. 

Finally, scenarios setting and re-setting a belongsTo relationship wrongly keeps `changeset.isPristine === false`.

In respect to an **object attribute**, I guess the problem might be related to comparison involving **null** and **undefined** values.

In respect to an **object belongsTo relationship**, I guess the problem might be related to comparison involving **object reference**, **null** and **undefined**.

**Comment by poteto** [comment]
Thanks for the feedback, I'll address it tonight!

**Comment by fknoll** [comment]
Realizing that `changeset.changes` currently is a not really a **"list of changes"**, but a **"list of touches"**, I have developed two util functions `ChangesetPropertyIsDefactoDirty` and `ChangesetIsDefactoDirty`.

I do not claim those two functions to be final/complete, but they serve my current purpose of tracking changes to an Ember Data model/record.

Here they are:

**// app/utils/changeset-property-is-defacto-dirty.js**
```
import Ember from 'ember';

export function hasDifferentValues(valueOfChangesetAttribute, valueOfModelAttribute) {

  let isDirty = false;

  let isPropertyABelongTo = (
    Ember.typeOf(valueOfModelAttribute) === 'instance'
  );

  let isModelAttributeAnEmptyBelongTo = (
    isPropertyABelongTo &&
    Ember.isEmpty(Ember.get(valueOfModelAttribute, "id"))
  );

  let isModelAttributeAFilledBelongTo = (
    isPropertyABelongTo &&
    (!Ember.isEmpty(Ember.get(valueOfModelAttribute, "id")))
  );

  let isChangesetAttributeAnEmptyBelongTo = (
    isPropertyABelongTo &&
    (Ember.typeOf(valueOfChangesetAttribute) === 'null')
  );

  let isChangesetAttributeAFilledBelongTo = (
    isPropertyABelongTo &&
    (Ember.typeOf(valueOfChangesetAttribute) !== 'null') &&
    (!Ember.isEmpty(Ember.get(valueOfChangesetAttribute, "id")))
  );

  let differentValues = (

    (
      isModelAttributeAnEmptyBelongTo &&
      isChangesetAttributeAFilledBelongTo
    ) ||

    (
      isModelAttributeAFilledBelongTo &&
      isChangesetAttributeAnEmptyBelongTo
    ) ||

    (
      (
        isModelAttributeAFilledBelongTo &&
        isChangesetAttributeAFilledBelongTo
      ) &&
      (
        Ember.get(valueOfModelAttribute, "id") !==
        Ember.get(valueOfChangesetAttribute, "id")
      )
    ) ||

    (
      (!isPropertyABelongTo) &&
      (
        Ember.isEmpty(valueOfModelAttribute) &&
        (!Ember.isEmpty(valueOfChangesetAttribute))
      )
    ) ||

    (
      (!isPropertyABelongTo) &&
      (
        (!Ember.isEmpty(valueOfModelAttribute)) &&
        Ember.isEmpty(valueOfChangesetAttribute)
      )
    ) ||

    (
      (!isPropertyABelongTo) &&
      (
        (!Ember.isEmpty(valueOfModelAttribute)) &&
        (!Ember.isEmpty(valueOfChangesetAttribute))
      ) &&
      (
        valueOfModelAttribute !==
        valueOfChangesetAttribute
      )
    )

  );

  if (differentValues) {

    isDirty = true;

  } // end-if

  return isDirty;

} // end-function hasDifferentValues()


export default function(property, model, changeList) {

  let isDirty = false;

  let index = changeList.findIndex(x => x.key === property);

  if (index > -1) {

    let valueOfChangesetAttribute = changeList[index].value;
    let valueOfModelAttribute = Ember.get(model, property);

    isDirty = hasDifferentValues(valueOfChangesetAttribute, valueOfModelAttribute);

  } // end-if

  return isDirty;

} // end-function()
```

**// app/utils/changeset-is-defacto-dirty.js**
```
import Ember from 'ember';
import {hasDifferentValues} from './changeset-property-is-defacto-dirty';

export default function (model, changeList) {

  let isDirty = false;

  for (let i = 0;  i < changeList.length; i++) {

    let key = changeList[i].key;
    let valueOfChangesetAttribute = changeList[i].value;
    let valueOfModelAttribute = Ember.get(model, key);

    if (hasDifferentValues(valueOfChangesetAttribute, valueOfModelAttribute)) {

      isDirty = true;
      break;

    }  // end-if

  } // end-for

  return isDirty;

} // end-function()
```

**Comment by bgentry** [comment]
I'm not sure this is working as expected. I created a fork of the ember-changeset-validations twiddle and updated it to point at the latest version of that addon. I also altered it so the object being created (the user Jim Bob) is valid from the start: https://ember-twiddle.com/65294d77c2da9f9c551b143170ca0574?numColumns=3&openFiles=routes.application.js%2Ctemplates.application.hbs%2Cvalidations.user.js

Each time you save, it outputs `changeset.get('changes')` to `console.log()`. You can repeatedly click save without touching the fields, and every time an array of 5 changes is logged. Shouldn't it be empty after the first save?

**Comment by poteto** [comment]
Thanks for reporting @bgentry, I have determined that the cause of the issue is actually the `validate` method. There is a bug now where calling `validate` will always set the changeset's list of changes - this should instead only set errors. I'm tracking that issue in #132 and will fix as soon as I can
