### ISSUE TITLE
Original/old value of a property of the changeset object

### ISSUE THREAD

**Issue by fknoll** [DockYard/ember-changeset#114]
In documentation for **change** at https://github.com/DockYard/ember-changeset#change it is written:

**You can use this property to locate a single change:**
```
{{#if changeset.change.firstName}}
  <p>You changed {{changeset.firstName}} to {{changeset.change.firstName}}!</p>
{{/if}}
```
But, I seems like `{{changeset.change.firstName}}` always contains exactly the same value as `{{changeset.firstName}}`.

I am not surprised to find the new value of `firstName` in `{{changeset.firstName}}`. I have no expectations about what to find in  `{{changeset.change.firstName}}`.

Anyway, where do I find the original/old value of a property of the changeset object ?

**Comment by bugant** [comment]
@fknoll maybe the "bug" is in the doc's example... I mean you can have it like the following (supposing that you created the changeset starting from `model`):

    {{#if changest.change.firstName}}
       <p>You changed {{model.firstName}} to {{changeset.change.firstName}}!</p>
    {{/if}}

**Comment by poteto** [comment]
Yeah the readme is out of date, I will fix it. Really I need to deprecate `changeset.change.foo` since `changeset.foo` gives you the same thing and will no longer always return the model's current value.

**Comment by fknoll** [comment]
Thank you @bugant and @poteto - I got it :-)

I was under the impression that the `changeset` had a reference to the `model/object` used when I created/initialized the `changeset`.

To make my templates **as generic as possible**, I would prefer to reference the `changeset` for original/old values - not the `model/object` used when creating the `changeset`.

In addition, when I (further down the path) am going to "componentize" my code, I think I would prefer only to supply a `changeset` as a parameter; not also the `model/object` used when creating the `changeset`. Or, maybe I am wrong, maybe it should be the responsibility of components to create the `changeset`?

Anyway, case closed :-)

**Comment by fknoll** [comment]
Well, on second thoughts, I do not really think this issue is closed … 

From my point of view, it would be very helpful for `ember-changeset`  to support:

```
changeset.isPristine
changeset.isDirty
changeset.isTouched
```

```
changeset.property.isPristine
changeset.property.isDirty
changeset.property.isTouched
```

Additionally, I would prefer the changelist `changeset.changes` **not to include touches** (original value equal to current value), but **only real changes** (original value not equal to current value).

If relevant, a touchlist `changeset.touches` could be introduced.

**Comment by bradcrawford** [comment]
Related to the above comment by @fknoll to not include touches, some odd behaviour that I have noticed is that after calling `changeset.validate()` immediately after the changeset has been created, (I am validating the initial state of the model) causes `changeset.isDirty` to be flagged true, even though there are no actual changes made. Is this intentional @poteto ?

**Comment by poteto** [comment]
Are there errors on the changeset? @bradcrawford
