### ISSUE TITLE
with ember >= 2.7.0 it's impossible to set undefined to an new changesets field

### ISSUE THREAD

**Issue by makepanic** [DockYard/ember-changeset#115]
With ember@2.7.0 the behavior of `Ember.set` was changed to not modify the host object if [the value is already there](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/property_set.js#L62-L63).
That means if one does `a = {};Ember.set(a, 'foo', undefined);Object.keys(a)`, `a` won't have the `foo` key. ( see https://github.com/emberjs/ember.js/issues/14270 ).

In context of changeset that means that a change that tries to set `undefined` to the changeset `CHANGES`, it won't be "tracked" and not set on the `CONTENT` object on `execute()`.

I'm not sure if this is a problem for changeset. If it is and you think this is a bug/regression in ember, please comment on https://github.com/emberjs/ember.js/issues/14270 .

A possible use-case would be a `one-way-select` (with `promptIsSelectable`) that represents a country selector, where blank means `all countries`. 
If the user wants to change an item to `all countries`, where the country was previously set to a specific country, `undefined` would be set, which in turn wouldn't be set on the `CHANGES` object, because previously `get(obj, 'country')` was already `undefined`.

**Comment by poteto** [comment]
This does affect `ember-changeset`, but ultimately I want the execution of a changeset to be aligned with how you would set properties on the model directly via `set` and `setProperties`. Let's take the discussion to that issue in ember core.

**Comment by Charizard** [comment]
Any temporary fix for the above mentioned `one-way-select` use case till `set` and `setProperties` are fixed in ember core?
