### ISSUE TITLE
Ember CP Validations + Ember Changeset

### ISSUE THREAD

**Issue by offirgolan** [DockYard/ember-changeset#120]
Hi there! 

I have been working on an addon to integrate ember-cp-validations with ember-changeset. Unfortunately my lack of deep understanding of this library holds me back from releasing it into the wild. I was hoping someone here can do a quick review to make sure Im not doing anything too stupid or something that can be easily broken further down the line. Any help at all is appreciated 😄 

➡️ [ember-changeset-cp-validations](https://github.com/offirgolan/ember-changeset-cp-validations)

**Comment by poteto** [comment]
Added a link in #124, thanks for creating this!
