### ISSUE TITLE
Changeset is always pristine when invalid

### ISSUE THREAD

**Issue by Keeo** [DockYard/ember-changeset#129]
While working on my project I noticed that isPristine returns true when isValid is false. This is definitely not  expected. Is there any story behind this? [Here](https://github.com/Keeo/ember-changeset-is-pristine/pull/1/files) is full, working example.

**Comment by jklapuch** [comment]
It is the opposite of isDirty. `pristine changeset is one with no changes.` But you can have an attribute of model that is required, the model behind changeset may be a new or empty and therefore does not have any value (valid or invalid). If you do need a button that is disabled until a value is filled, you can add `disable={{changest.isPristine}}`. Changeset starts with isPristine=true and isValid=false.

**Comment by Keeo** [comment]
But pristine changeset is clearly not one with no changes. Look at this example.
```js
const model = this.get('model'); //model.name === 'valid-name'
// name: [validateLength({max: 100, min: 2})]
const changeset = new Changeset(model, lookupValidator(validations), validations);
const log = function() {
  console.log(`isPristine: ${changeset.get('isPristine')}, isValid: ${changeset.get('isValid')}, orig: '${model.get('name')}', new: '${changeset.get('name')}'`);
};

log(); // isPristine: true, isValid: true, orig: 'valid-name', new: 'valid-name'
changeset.set('name', 'valid-but-different');
log(); // isPristine: false, isValid: true, orig: 'valid-name', new: 'valid-but-different'
changeset.set('name', 'x');
log(); // isPristine: true, isValid: false, orig: 'valid-name', new: 'x'
```

When the value is not valid `isPristine` returns `true`.

**Comment by jklapuch** [comment]
Do you have a working example? It works differently for me. Without call any method on changeset, isPristine will be false when I type anything to my form.

**Comment by Keeo** [comment]
Just quick check - do you have `v1.2.0`?

**Comment by Keeo** [comment]
Anyway [here](https://github.com/Keeo/ember-changeset-is-pristine/pull/1/files) is full, working example. Just clone, `ember serve`, open `http://localhost:4200/` and check console output.

**Comment by jklapuch** [comment]
Okay, now I see it and you're right. I see that the property `CHANGES `is updated only if the new value is valid. I see that isPristine is true when `CHANGES `is the same as the underlying object. So I agree with you that it's a little confusing when changeset can be set to an invalid value and isPristine remains true.

**Comment by poteto** [comment]
@jklapuch I made it so `isPristine` only watches changes because errors will never get applied onto the model. So it's still "pristine" in the sense that nothing has changed. Does that make sense?

**Comment by Keeo** [comment]
Why is it so hard to have `isPristine` work like described in docs :(

**Comment by poteto** [comment]
I'm not sure what the confusion is, "pristine" means that the model will be left unchanged if the changeset is executed. In the example you posted above:

```js
changeset.set('name', 'valid'); 
changeset.set('name', 'some invalid value');
```

The second `set` will clear the first change and make it an error instead. There are now no changes and one error on the changeset. In other words, the changeset is pristine!

What is the usecase that you need `isPristine` to be `false` when the changeset is invalid?

**Comment by Keeo** [comment]
Sorry! I see where is problem now. Because english is not my native language and i don't think there is fitting word for it in my language I used `blackbox` in my mind as a substitution. So when you rewrite that statement with blackbox instead `A pristine blackbox is one with no changes.` it starts to make sense why I see `blackbox` that contains some internal changes that make it invalid as not pristine one.

Anyway, I wanted to check if user made any changes to form before closing it.
