### ISSUE TITLE
Computed properties not working on changeset

### ISSUE THREAD

**Issue by MarkPSmith** [DockYard/ember-changeset#159]
I think this is probably a duplicate of #145.  Basically, when I have a model that has computed properties, and create a changeset from it, the computed properties don't function on the changeset.  I've created a twiddle recreating this here:

[ember-changeset does not work with computed properties](https://ember-twiddle.com/85866dfbe0fdd00a340309f0662646de?openFiles=routes.application.js%2C)

Is there a workaround, or is the use of CPs not supported?

**Comment by poteto** [comment]
It is not supported. A changeset is a representation of the changes that should be applied to a model, and not the model itself. If you **really** need to, you can define an ad-hoc computed on the changeset instance:

```js
let changeset = new Changeset(model, validatorFn);
Ember.defineProperty(changeset, 'myComputed', Ember.computed('change.foo', 'change.bar', function() {
  return Ember.get(this, 'change.foo') + Ember.get(this, 'change.bar');
}));

changeset.get('myComputed');
```

**Comment by MarkPSmith** [comment]
That makes perfect sense.  Thank you!

**Comment by MarkPSmith** [comment]
Just a follow up for anyone finding this in the future.  It turns out that the computed props on my model were really a code smell.  I had them there for display purposes only and it made more sense just to rewrite everything to put the display logic in the component instead.

**Comment by abobwhite** [comment]
@MarkPSmith Ember models are inherently UI-specific so I have never considered it "bad" to include display data  in an ember model, where it makes sense and is solely computed based on model properties. For example, I display a different label depending on a model property. I suppose a helper or component would certainly be ideal but I don't think it's necessarily a code smell.
