### ISSUE TITLE
Delete new model when call rollback()

### ISSUE THREAD

**Issue by minhnq013** [DockYard/ember-changeset#160]
Hi, 

I am currently using the changeset to wrap around new model record and to my surprise, when I called "rollback()" on the changeset the new model was not removed.

It is probably uncertain whether rollback should delete the record, but is it possible to provide a function that would have same behavior as "rollbackAttributes" of DS.Model ?

Thanks a lot for the great addon,

**Comment by poteto** [comment]
Please destroy the model directly instead. The changeset is not a replacement for the model, it's only a representation of the changes to be applied to a model.

**Comment by chekmare** [comment]
Unfortunately there is no easy way to access underlying model.

**Comment by poteto** [comment]
You have to pass the model into the changeset, correct? If you keep that model variable around you can destroy it.
