### ISSUE TITLE
Modified property twice in a single render

### ISSUE THREAD

**Issue by arenoir** [DockYard/ember-changeset#162]
I have run into a very hard to trace double render issue that seems to stem from the initial validation of one of my models.   This is in use with the `ember-changeset-validations` plugin. 

I am instantiating the changeset within a computed property like so and am getting a double render error when used in a basic form.

```
  changeset: computed('model', function() {
    const model = this.get('model');

    return new Changeset(model, lookupValidator(validations), validations);
  }),

```

If I remove the validationMap everything works.  Hence the question "what is the `validationMap` and why would it be mutating the changeset?"

**Comment by poteto** [comment]
I would not recommend creating a changeset in a CP, as it will be creating multiple changesets if that CP fires again (which is likely the cause of your double render issue). Please do it once on the `init` hook instead.

**Comment by arenoir** [comment]
It happens in both init or a cp

**Comment by poteto** [comment]
Stacktrace please?

**Comment by arenoir** [comment]
Stack trace: https://gist.github.com/arenoir/2e1f53a39eb292309afef7bce3e0d384

FYI... I am changing a working form from using ember-cp-validations to ember-changeset-validations.

**Comment by poteto** [comment]
How are you using `timeEntry.changeset.date`? The validationMap doesn't do anything when included in the changeset factory. It is only used when the `validate` method on the changeset is called.

**Comment by arenoir** [comment]
It is very strange as I am only using `timeEntry.changeset.date` to display the date in the modal header.  

There are a couple things going on. One the modal is rendered once, and then the form is updated when the model changes.  Two the bootstrap form is calling the validate method on render and rerender. 

I just fond it strange that the whole thing worked when the validationMap was removed or actually the process went it worked until I added the validation map.   So it got me thinking if the validate function is built using the factory what is the map used for?  

Anyhow I am refactoring the modal and doing a full render every time the model is changed. 

Thanks for taking some time to look at this.

**Comment by poteto** [comment]
Could you use the `date` property on the model / object instead of the changeset? The changeset is really a representation of the _changes_ to be applied, and it shouldn't be used as a "double" for the model. I'm unsure what the cause of the double render is, but from what you describe it seems like it's being caused by the `validate` method being called. This validates and sets properties internally on the changeset, and that might be the cause.

**Comment by arenoir** [comment]
Once working the date needs to trigger a date picker and reflect the change.  I didn't mean to blame   the changeset for the issue I was just trying to understand how it worked.  It appears that you can create a changeset with a model and a validate function?  Which leads to the question what is the validationMap?

**Comment by poteto** [comment]
Yes, I understand, but the validation map on its own is not the cause for your double render. Somewhere in your application the changeset is being modified more than once in a single render. Because the `validate` method requires a validation map, when you leave it out `validate` becomes a no op. And as I mentioned earlier, `validate` will cause some internal properties to be set.

How is your bootstrap form calling `validate`?

**Comment by arenoir** [comment]
The following [addon](https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/master/addon/components/bs-form.js#L17) calls validate on init of the form.  

I am still confused as to how the validations work with or without the validaitonMap?

**Comment by poteto** [comment]
The changeset expects a function that returns a validator (ie what `lookupValidator` is returning) as a 2nd argument. The 3rd argument - the validation map - is optional.

None of the above is relevant to your issue. Do one of the following:

1. Override `bs-form` and make `_initValidation` a no-op
2. Remove the use of `timeEntry.changeset.date`

The combination of the 2 is the cause for the double render.

**Comment by poteto** [comment]
And for more context about how the validator lookup function is used, please read the [usage section](https://github.com/DockYard/ember-changeset#usage) of the readme

**Comment by arenoir** [comment]
Thank you and I apologize for my denseness. I understand that passing in the validationMap shouldn't affect the mutation of the changeset but for some reason it is.  Since it is optional and removing it fixes the issue I will do so.  

The 'ember-changeset-validations' [readme](https://github.com/DockYard/ember-changeset-validations/blame/master/README.md#L102 ) describes placing the validations object as the validationsMap. 

One other thing to mention is the difference between the `ember-changeset-validations` [implementation](https://github.com/DockYard/ember-changeset-validations/blob/master/addon/helpers/changeset.js#L15) of the validationsMap and the `ember-changeset-cp-validations` [implementation](https://github.com/offirgolan/ember-changeset-cp-validations/blob/master/addon/index.js#L13). ember-changeset-cp-validations creates a object with the validatable attributes as keys and true as the value.  And again one works and the other does not go figure?

**Comment by arenoir** [comment]
So the `validationMap` is used only when calling the `validate` function on the changeset.  If the `validationMap` is empty the validate function does nothing even if you pass a key in.  However when attributes are mutated it will run the validation function for each modified attribute.  So I wouldn't say the `validationMap` is optional.  It seems obvious now but the `validationMap` is a list of attributes to run through the validation function when `validate` is called without a key.  I assumed all attributes were just past through the validation function.   IMO the `validationMap` should not be required to validate with a key.
