### ISSUE TITLE
Changeset is not working in 2.10 and beyond

### ISSUE THREAD

**Issue by mdcoopir** [DockYard/ember-changeset#168]
We are using ember-changesets.  They are working in 2.9.1.  We tried to upgrade to the latest Ember version, but the changeset is not compatible with ember version 2.10.1, 2.11 or 2.12.  Where ever we have used the changeset object on a view, it renders empty and has no error logs in console.

**Comment by poteto** [comment]
Needs more info on how you're using the addon. FYI the [demo](https://bit.ly/ember-changeset-demo) is running on `2.12` and it works fine.

**Comment by mdcoopir** [comment]
We found the problem.  We were using dots instead of slashes in the URL for the components.  Use slashes and everything works fine.

**Comment by sandstrom** [comment]
@mdcoopir can this issue be closed?
