### ISSUE TITLE
Ember data models isNew

### ISSUE THREAD

**Issue by scottkidder** [DockYard/ember-changeset#198]
Is there a way to call into the internal model to get something like model.isNew?

**Comment by simonc** [comment]
@scottkidder Hi. Did you find a solution that made you close this issue? Thanks

**Comment by scottkidder** [comment]
Hi @simonc I eventually found an issue where @poteto stated something to effect of 'the changeset is not a replacement for your model You should keep a reference to your model for these types of operations.' and I found that to be the best solution.

**Comment by simonc** [comment]
@scottkidder fair enough. Thanks for your feedback :wink:
