### ISSUE TITLE
isDirty not updated after setting invalid value for property

### ISSUE THREAD

**Issue by andrewpye** [DockYard/ember-changeset#203]
I have a use case where I'm depending on a changeset's `isDirty` flag to warn the user of unsaved changes when they leave a page. I'm finding that if I have validations on a property and I set an invalid value on that property, the changeset's `isDirty` flag doesn't update, e.g.

```javascript
// validations
export default {
  someString: validatePresence(true)
};

// component
changeset.get('isDirty'); // => false

changeset.set('someString', null);
changeset.get('isDirty'); // => still false

changeset.set('someString', 'something');
changeset.get('isDirty'); // => true
```

In my use case this means that the user can edit a field to something invalid, and leave the page without being alerted to the problem (and to the fact that their change will be thrown away).

Is this intentional behaviour?

**Comment by msalahz** [comment]
Hi @andrewpye, As mentioned in addon docs
>IsDirty Returns a Boolean value of the changeset's state. A dirty changeset is one with changes.

So if `someString` initial value is `null`, setting it to null will not change it's state and shouldn't change `IsDirty` flag.

Please let me know if this is not the case ?

**Comment by andrewpye** [comment]
@msalahz thanks for getting back to me!

I should have been clearer - what my example doesn't show is that the problem I described was for when the changeset's underlying model initially had a valid, non-null value for the property in question. So what I should have written is this:

```javascript
// validations
export default {
  someString: validatePresence(true)
};

// component
// start with a changeset backed by a model with a valid value for `someString`:
changeset.get('isValid'); // => true
changeset.get('isDirty'); // => false

changeset.set('someString', null);
changeset.get('isDirty'); // => still false

changeset.set('someString', 'something');
changeset.get('isDirty'); // => true
```

**Comment by msalahz** [comment]
@andrewpye: I can see thar  [here](https://ember-twiddle.com/e5eaa7bee6ed76257f5a62e618c315e8?openFiles=controllers.application.js%2C). Will try to look into it this weekend

**Comment by msalahz** [comment]
Sorry here is the correct twiddle url https://ember-twiddle.com/d4afc893cbae670ecc3901ae5977c3cf?openFiles=controllers.application.js%2C

**Comment by nucleartide** [comment]
@andrewpye That seems to be expected behaviour, see https://github.com/DockYard/ember-changeset/blob/5d973b15387b5905506c1e3af2b72dcd72dca066/tests/unit/changeset-test.js#L132.

However, you could check if it's dirty *or* if it's invalid. For example:

```js
const hasUnsavedChanges = changeset.get('isDirty') || changeset.get('isInvalid');
```

Lemme know if that works!

**Comment by andrewpye** [comment]
@nucleartide thanks for pointing that out! Your suggestion would give the desired result, but feels more like a workaround than a fix to me; semantically, it doesn't make any sense for `hasUnsavedChanges` to depend on the validity of the changeset - a change is a change, whether it's valid or not, and validity is a separate matter as far as I'm concerned, and should be handled separately.

The danger of your suggestion of `hasUnsavedChanges` depending on the changeset's `isInvalid` property is that it's the sort of thing that another dev could easily remove when tidying up or refactoring code, since from a naming point of view, "unsaved changes" shouldn't have any relation to "validity" at all...

**Comment by nucleartide** [comment]
@andrewpye I definitely see what you mean, maybe it'd be more clear to check for changes/errors? So:

```js
const hasUnsavedChanges = changeset.get('changes.length') > 0 || changeset.get('errors.length') > 0;
```

A changeset is a set of valid changes by definition, which is why we have to check errors too.

**Comment by andrewpye** [comment]
@nucleartide I suppose this issue comes about from the terminology - to me `changes` implies _all_ changes rather than just those that are valid, and in my mind validity would be determined based on validating the result of applying those changes to the underlying object. If I make a change, I expect the changeset to become dirty/have changes, regardless of whether that change is valid or not. To be fair, this is also outlined right there in the opening section of the readme, so I guess I'll have to go with your suggestions and leave comments in to stop other devs removing the errors/validity check.
