### ISSUE TITLE
Think about handling constraints

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-changeset#24]
Needs some kind of server interaction and possible adapter implementation

**Comment by dustinfarris** [comment]
I'm thinking something like this (works sort of locally):

```js
// in changeset#save
return content
  .save(options)
  .then(() => this.rollback())
  .catch(response => this.evaluateConstraints(response));


evaluateConstraints(response) {
  let content = get(this, CONTENT);
  let constraintErrors = get(this, CONSTRAINT)(content, response);
  mergeErrorsSomehow(constraintErrors);


// Some user-provided or included function
constraintFn(content, response) {
  // Could potentially inspect response for a server error or something
  // Otherwise if we're using ember-data the errors are stored on the model
  return content.get('errors.messages');  // or maybe iterate through each specific attr
}
```

**Comment by dustinfarris** [comment]
@poteto what do you think of this direction?  Should I start working on a PR or did you have something else in mind?

**Comment by poteto** [comment]
I need to think about it a little more, ideally I would like a constraint to be caught prior to saving. But that would mean your API would need to have some endpoint for eg to check uniqueness for a given email address. And technically you could do that right now with an asynchronous validator

**Comment by poteto** [comment]
The proposed solution is more of a feature to merge server side errors with the changeset, which could be a useful feature. It's not related to constraints in Ecto parlance though

**Comment by dustinfarris** [comment]
Oh? My understanding is that this is precisely what Ecto constraints do.  From their docs:

> Ecto changesets provide both validations and constraints which are ultimately turned into errors in case something goes wrong... constraints can only be checked in a safe way when performing the operation in the database. As a consequence, validations are always checked before constraints. Constraints won’t even be checked in case validations failed.

Basically swap out "database" with "backend API" and that's what I'm trying to accomplish here.

**Comment by poteto** [comment]
Ah yeah I got mixed up, my bad! My concern is that a server side error isn't necessarily always a constraint error, so it would not entirely be correct to call it a "constraint" on the addon's end. For example, having `uniqueConstraint` or `foreignKeyConstraint` methods on the changeset wouldn't be possible as we won't be able to tell from simply receiving the error response from the API. It would be more correct to simply have some method that merges server side errors (whatever they may be) onto the changeset. It might just be naming, but I think it's an important distinction to make. Not sure if I explained it well, let me know if it doesn't!

That API for adding errors could just be:

```js
changeset
  .save()
  .then(/* ... */)
  .catch((errors) => {
    errors.forEach((error) => {
      let key = ...
      let value = ... 
      let validation = ...
      changeset.addError(key, { value, validation });
    });
  });
```

**Comment by dustinfarris** [comment]
#46 is nice and I definitely think you're right that extracting specific constraint errors is over reaching.  It would be nice to have a pluggable way to have ember-data model errors propagated to the changeset on save.  With addErrors the user has to inspect the JSON API errors manually and add them accordingly every single time.  Recall that ember-data already does this for us on record.save.  I think we should push these errors to the changeset in a automated (but pluggable) fashion using something similar to what I sketched above

**Comment by poteto** [comment]
Agreed, extracting errors that are already set on the model instance would be very useful. Pluggable approach sounds good to me too 👍

**Comment by dustinfarris** [comment]
PR on its way
