### ISSUE TITLE
How to handle lists of things?

### ISSUE THREAD

**Issue by eventualbuddha** [DockYard/ember-changeset#4]
Let's say you have a model `A` that `hasMany` some other model `B`, and your form has a dynamic list of `B` that are editable all at once. How would you wire that up using ember-changeset? It seems like you'd want to have a changeset per `B` record as well and have the validation on the list of `B` be the aggregate of the child validation state, but… that sounds like lots of manual wiring, if it's even possible at all.

**Comment by poteto** [comment]
Good question! I think it would make the most sense for each model `B` to have its own changeset with its own validation, and not to have them apply to the entire list (although I could see someone trying to validate the length of the list for example). 

On a sidenote, I think I need to implement relationship support (#5) before I can think of a better solution for this
