### ISSUE TITLE
property not notified when using a validator

### ISSUE THREAD

**Issue by dustinfarris** [DockYard/ember-changeset#49]
I am getting the bug fixed in #47 when i pass a validator (either as an action or an ember-changeset-validators validation map).

```hbs
{{#with (changeset model (action "validate") as |changeset|}}
  <h2>{{changeset.email}}</h2>
  <input value={{changeset.email}} oninput={{action (mut changeset.email) value="target.value"}}>
{{/with}}
```

**Comment by poteto** [comment]
Can you make a twiddle to reproduce this issue?

**Comment by poteto** [comment]
https://gist.github.com/e31a6415a4e3134770d6875d110da30a

Works as expected
