### ISSUE TITLE
Handle relationships

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-changeset#5]

**Comment by wolfbiter** [comment]
+1, im very interested in this. especially since i dont know of a good solution in the ember community to tracking dirtiness on relationship changes

**Comment by curtisgr** [comment]
@poteto have you made any progress toward this issue?

**Comment by poteto** [comment]
This works

**Comment by curtisgr** [comment]
Would you recommend this as a way to track dirtiness of relationships in general?  I understand this project is about bring similar APIs and concepts from Ecto changeset to Ember, but being able to track dirtiness of relationships to me is a significant bonus and valuable outside of the Ecto changeset stuff.

**Comment by curtisgr** [comment]
To give some context, while I found this addon because I'm working with elixir and ember personally, my work uses django and ember, but would benefit from being able to track dirtiness of relationships.

**Comment by dyoganand** [comment]
@poteto is this already available??? It doesn't seem to be so, correct me if I'm wrong! 

I have a parent object A with a list of children B's (has-many association). I am doing `changeset A` and passing it to a component. Both A's properties and (in the list of B's) the B's properties are editable in the component. If I want to save, there are no issues. Now if I want to cancel the changes by `changesetA.rollback()` the original A's properties are untouched, but B's properties are affected.. To be precise, it works like a shallow copy.

**Comment by karellm** [comment]
@poteto I would greatly appreciate a pointer. Assuming I have an `post` that has many `tags`. When I'm editing the `post` and do `changeset.tags.pushObject(tag)`, it actually mutate the actual relationship. It would be nice to have a little bit of documentation on this support for relationships. Thanks!

**Comment by dyoganand** [comment]
Dear reply+005eef0ea251a2bd355382ccbf872593225c0457bf54cec792cf0000000114c5eb4192a169ce097a8906,We would like to acknowledge that we have received your email request.Our HR representative will be reviewing your request and will send you a personal response shortly. (usually within 48 working hours).Thank you for your patience.Regards,sriramv966 




FreshTeam , Applicant Tracking System powered by Freshdesk Inc.

**Comment by Kuzirashi** [comment]
I doubt this works. _changes object on changeset shows relationship (belongs to) is dirty even when id (and record) is the same.

**Comment by Duder-onomy** [comment]
As of right now, I don't think `ember-changeset` can properly support any relationships. If someone gets to this thread via frustrated googling, I highly recommend avoiding this library until there is documented relationship support. 
That being said, it is really nice to work with when the model has no relationship nesting. Good job team. Hope we can get some first class relationship support in here soon.
