### ISSUE TITLE
addError overwrites existing error for key

### ISSUE THREAD

**Issue by dustinfarris** [DockYard/ember-changeset#51]
Is this intended behavior?  If so we should mention in the docs.

Also, as an aside, addError is given an array for `validation` message from ember-changeset-validations, but is given a string in the docs and test.  Is this something we care about and/or will care about in future development?

**Comment by poteto** [comment]
Yes it is intentional. Would you like to open a PR for it?

It doesn't really matter what the value for `validation` is, it is dependent on the validation library. In the case of `ember-changeset-validations`, it's always an array. But in ember-changeset it doesn't have to.
