### ISSUE TITLE
validating single property causes value to rollback to last valid value

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-changeset#60]
To reproduce:

1. Enter invalid value in demo
2. Tab out
3. Input's value rollsback to last valid value

**Comment by dustinfarris** [comment]
This occurs when validating the entire changeset as well.

**Comment by poteto** [comment]
Good catch, thanks! I'm out today, but if anyone wants to have a stab at this, the `validate` method basically needs to only validate and set errors. If I'm not wrong the input resets because there is a change notified when validating, so it pulls the data again causing the reset to be the last (valid) value on `changes`.

**Comment by dustinfarris** [comment]
Possible this is something else, and/or I am not testing this properly.

This is passing without any changes:

```js
test('does not notify when not valid', function(assert) {
  let dummyModel = { name: 'John' };
  let dummyValidator = () => false;
  this.set('changeset', new Changeset(dummyModel, dummyValidator));

  this.render(hbs`
    <input
      id="name"
      value={{changeset.name}}
      onchange={{action (mut changeset.name) value="target.value"}}>
  `);

  assert.equal(this.$('#name').val(), 'John');
  this.$('#name').val('wrong').change();
  assert.equal(this.$('#name').val(), 'wrong');
  this.get('changeset').validate('name');
  assert.equal(this.get('changeset.errors.length'), 1);
  assert.equal(this.$('#name').val(), 'wrong', 'input value should not be reset to valid value');
});
```

**Comment by poteto** [comment]
It turns out this bug is semi-related to #59...
