### ISSUE TITLE
How to handle validators that return promises

### ISSUE THREAD

**Issue by brancusi** [DockYard/ember-changeset#70]
Hi,

Wondering how I can handle validators that return promises.

Trying to create a validator that checks if a name is available by calling some `api/name_check` service.

https://ember-twiddle.com/d4ec3c55c540d6da68da36ba79250590?fileTreeShown=false&openFiles=validations.user.js%2C

If you type anything in `firstName` you will notice `[object Object]` instead of a passing validation.

I noticed there was work done on handling validators that return promises, but I can't see how it actually works.

Thank you

**Comment by brancusi** [comment]
Simplified twiddle: https://ember-twiddle.com/d4ec3c55c540d6da68da36ba79250590?fileTreeShown=false&openFiles=validations.user.js%2C

**Comment by poteto** [comment]
@brancusi Thanks for opening this issue. This is actually a bug in `ember-changeset-validations`, so I will close this issue and reopen it there.

**Comment by poteto** [comment]
See https://github.com/DockYard/ember-changeset-validations/issues/51
