### ISSUE TITLE
Return a new object after applying a changeset

### ISSUE THREAD

**Issue by cafreeman** [DockYard/ember-changeset#82]
A handy optional feature would be the ability to apply a changeset and have it return a *new* object, with the changes, (assuming they're valid). This way, we'd have the option to proxy over to the original model, *plus* the ability to apply changesets immutably and curry the result of changeset executions with other actions/functions.

If you want to point me in the right direction, I'd be happy to work on this myself and open a PR.

@poteto

**Comment by cafreeman** [comment]
Just kidding! After talking with @poteto it sounds like this is probably better suited to being a separate thing in one way or another, so I'm gonna go ahead and close this.

**Comment by dustinfarris** [comment]
@cafreeman i am thinking about the same thing here.  did you ever go further with this?
