### ISSUE TITLE
isValid on init

### ISSUE THREAD

**Issue by brancusi** [DockYard/ember-changeset#91]
Hi,

Love this addon, thanks again for putting it together.

Question regarding isValid when you first create the changeset. Is there a way to have the changeset run it's validate function when it is first created?

I would like to be able to create a changeset and be able to test the isValid prop right away in the template.

Notice in this twiddle even though the model is invalid, it shows as valid on init: [Twiddle](https://ember-twiddle.com/d4ec3c55c540d6da68da36ba79250590?fileTreeShown=false&openFiles=templates.components.edit-user.hbs%2C)

Thanks

**Comment by poteto** [comment]
Hey, you can just do `changeset.validate()` when it first renders. For example you could do that on the component's `didInsertElement` hook.

**Comment by Geokoumpa** [comment]
Hey @poteto, thanks for your great addons. I am trying to use ember-changet-validations with ember-form-for, however when hitting submit whithout filling out any fields, the changeset is always valid (although it shouldn't) and save is executed. If I type something invalid, it works fine and errors are shown as expected.

Does this sound like a mistake of mine, an ember-form-for bug, or an ember-changeset bug?

```
{{#form-for changeset submit=(action 'save') reset=(action 'cancel') as |f|}}
  {{f.text-field "name" required=true}}
  {{f.submit "Save"}}
{{/form-for}}
```

```
export default Ember.Controller.extend({
  actions: {
    save(changeset){
      let controller = this;
      changeset.validate().then(()=>{
        if (changeset.get('isValid')) {
          let savePromise = changeset.save().then(function(){
            controller.transitionToRoute('index');
          })
          return savePromise;
        } else {
         ...
        }       
      })
    },
    cancel(changeset){
      this.get('model').destroyRecord();
      this.transitionToRoute('index');
    }
  }
});
```

```
export default {
    name: [
        validatePresence(true),
        validateLength({ min: 4 })
    ]
};

```

**Comment by yaodong** [comment]
I had the same issue. Calling `changeset.validate()` in `didInsertElement` didn't fix it.

It's turned out I forget the third argument when creating a Changeset in JavaScript.

```js
new Changeset(model, lookupValidator(EmployeeValidations), EmployeeValidations)
```
